local t = require("tests.runner")
local fs_mock = require("tests.mocks.fs")
local tu_mock = require("tests.mocks.textutils")
local turtle_mock = require("tests.mocks.turtle")

t.describe("mock fs", function()
  t.it("writes, reads, moves, deletes", function()
    fs_mock._reset()
    local h = fs_mock.open("/foo.txt", "w")
    h.write("hello")
    h.close()
    t.assert_true(fs_mock.exists("/foo.txt"))
    local r = fs_mock.open("/foo.txt", "r")
    t.assert_eq(r.readAll(), "hello")
    r.close()
    fs_mock.move("/foo.txt", "/bar.txt")
    t.assert_false(fs_mock.exists("/foo.txt"))
    t.assert_true(fs_mock.exists("/bar.txt"))
    fs_mock.delete("/bar.txt")
    t.assert_false(fs_mock.exists("/bar.txt"))
  end)
end)

t.describe("mock textutils", function()
  t.it("round-trips nested tables", function()
    local s = tu_mock.serialise({ a = 1, b = { c = "x", d = true }, e = {1,2,3}})
    local v = tu_mock.unserialise(s)
    t.assert_deep_eq(v, { a = 1, b = { c = "x", d = true }, e = {1,2,3}})
  end)
  t.it("returns nil on garbage input", function()
    t.assert_nil(tu_mock.unserialise("not valid lua }}}"))
  end)
end)

t.describe("mock turtle", function()
  t.it("moves forward, updating position and fuel", function()
    turtle_mock._reset()
    turtle_mock._setFuelLimit(1000)
    turtle_mock._setFuel(100)
    t.assert_true(turtle_mock.forward())
    local p = turtle_mock._getPos()
    t.assert_eq(p.z, 1)
    t.assert_eq(turtle_mock.getFuelLevel(), 99)
  end)
  t.it("is blocked by placed blocks", function()
    turtle_mock._reset()
    turtle_mock._setBlock(0, 0, 1, { name = "minecraft:stone" })
    local ok, err = turtle_mock.forward()
    t.assert_false(ok)
    t.assert_true(err:match("obstruct"))
  end)
  t.it("digs forward and picks up the block into inventory", function()
    turtle_mock._reset()
    turtle_mock._setBlock(0, 0, 1, { name = "minecraft:cobblestone" })
    t.assert_true(turtle_mock.dig())
    t.assert_nil(turtle_mock._getBlock(0, 0, 1))
    local it = turtle_mock.getItemDetail(1)
    t.assert_eq(it.name, "minecraft:cobblestone")
  end)
end)
